
export const ACTION_EDIT_ALBUM = 'ACTION_EDIT_ALBUM';
export const ACTION_SUBMIT_EDITS = 'ACTION_SUBMIT_EDITS';
export const ACTION_DELETE_RECENT_EDIT = 'ACTION_DELETE_RECENT_EDIIT';
export const ACTION_LOAD_ALBUMS = 'ACTION_LOAD_ALBUMS';
export const ACTION_ADD_NEW_ALBUM = 'ACTION_ADD_NEW_ALBUM';

